<?php
return array(
	 "Googlebot" ,
	 "Feedfetcher-Google" ,
	 "Mediapartners-Google" ,
	 "Baiduspider+" ,
	 "Yahoo" ,
	 "Microsoft-WebDAV-MiniRedir" ,
	 "msnbot" ,
	 "msnbot-media" ,
	 "Webdup/0.9" ,
	 "iaskspider" ,
	 "Sogou web spider" ,
	 "YodaoBot" ,
	 "ia_archiver Alexa" ,
	 "Twiceler-0.9" ,
	 "Indy Library" ,
	 "QihooBot" ,
	 "Gigabot Gigabot" ,
	 "AliWaWa" ,
	 "spider" ,
	 "Spider" ,
	 "bot" ,
	 "Bot" ,
	 "WorldSearch" ,
 );