<?php
//用户中心测试
return array(
	'title'=>'Dialnopin orders',
	'admin'=>'orders',
	'func'=>array(
		"充值卡记录 <br>http://beta.dialnopin.com/orders/?act=card_info",
		"充值卡记录 - 显示当前登录用户的PIN, Card name, 绑定的电话号码和卡余额",
		"充值卡记录 - 点击绑定的电话号码连接至 '无PIN拨号设定' 功能",
	    "",
		"无PIN拨号设定 <br>http://beta.dialnopin.com/orders/?act=ani_update",
		"无PIN拨号设定 - 显示当前用户绑定的电话号码",
		"无PIN拨号设定 - 用户可以删除, 增加绑定电话号码",
        "",
        "历史订单记录 <br>http://beta.dialnopin.com/orders/?act=history",
        "历史订单记录 - 显示当前用户过往的交易记录",
        "",
        "电话卡在线充值 <br>http://beta.dialnopin.com/orders/?act=checkout_billing",
        "电话卡在线充值 - 用户选择要充值的金额",
		"电话卡在线充值 - 显示用户的Billing address信息",
		"电话卡在线充值 - 用户可以输入信用卡信息",
		"电话卡在线充值 - 提交时自动保存用户的Billing address信息",
		"电话卡在线充值 - 充值后, 在'历史订单记录'功能中, 对应添加刚才的充值记录",
	    "",
	    "电话卡在线充值注意(如下功能仅在测试期间生效)",
		"电话卡在线充值 - 目前的充值金额为选择金额的1%, 即$20 -> $0.2, $50-> $0.5",
		"电话卡在线充值 - 目前没有启用信用卡连接银行付款部分(如需启用, 我这里可以开通)",
	    "电话卡在线充值 - 付款功能已连接ACI端. 当提交订单时, ACI那里的金额会反映出来",
        "",
        "更新账户信息 <br>http://beta.dialnopin.com/orders/index.php?act=customer_update",
        "更新账户信息 - 自动加载用户信息并在界面显示",
        "更新账户信息 - 提交页面时, 检查用户是否输入了当前密码",
        "更新账户信息 - 提交页面时, 如果用户更改密码, 检查2次输入的密码是否一致",
        "",
        "更新地址簿 <br>http://beta.dialnopin.com/orders/index.php?act=address_book",
        "更新地址簿 - 自动加载用户信息并在界面显示",
        "更新地址簿 - 提交页面时, 对带'*'的栏位进行长度检查",
        "",
        "后台订单查看 <br>http://beta.dialnopin.com/admin/orders/",
        "后台订单查看 - 按照时间倒序顺序加载订单列表",
        "后台订单查看 - 点击'Refund'跳转至退款界面",
        "",
        "退款 <br>http://beta.dialnopin.com/admin/orders/?act=refund",
        "退款 - 根据输入的Order ID进行退款",
        "退款 - 订单号错误时, 不进行退款",
        "",
        "退款(如下功能仅在测试期间生效)",
        "退款 - 目前没有启用信用卡连接银行付款部分(如需启用, 我这里可以开通)",
        "退款 - 付款功能已连接ACI端. 当提交订单时, ACI那里的金额会反映出来",
	),
);
