<?php
/**
 * 相应的执行程序在 /admin/page/Lib/plugins/page_plugins_{$key}.php
 * 所有admin下的link都是相对 '/'.AppName.'/' 的
 */
return array(
	'pictext'=>array(
		'name'=>'图文单元',
		'note'=>'图文组［单个/多个］（图片/文字链）',
		'appact'=>'page_pictext',
		'admin'=>array(
			array('title'=>'管理','link'=>'setup/pictext.php?pid=$pid&tab=home&appid=$itemid'),
		),
		'config'=>array(
			'picnums'=>array(
				'name'=>'图片数量',
				'type'=>'input',
				'defaultValue'=>1,
			),
			'type'=>array(
				'name'=>'类型',
				'type'=>'radio',
				'init'=>array(
					array('name'=>'图片','value'=>'picture'),
					array('name'=>'文章','value'=>'article'),
				),
				'defaultValue'=>'article',
			),
			'width'=>array(
				'name'=>'宽度',
				'type'=>'input',
				'defaultValue'=>200,
			),
			'height'=>array(
				'name'=>'高度',
				'type'=>'input',
				'defaultValue'=>150,
			),
			'picTitleLength'=>array(
				'name'=>'标题长度',
				'type'=>'input',
				'defaultValue'=>40,
			),
			'picSumaryLength'=>array(
				'name'=>'描述长度',
				'type'=>'input',
				'defaultValue'=>100,
			),
			'fields'=>array(
				'name'=>'显示要素',
				'type'=>'checkbox',
				'init'=>array(
					array('name'=>'图片/视频','value'=>'box'),
					array('name'=>'描述摘要','value'=>'text'),
					array('name'=>'内容编辑器','value'=>'editor'),
				),
				'defaultValue'=>'box,text',
			),
			'islist'=>array(
				'name'=>'列表页导航',
				'type'=>'select',
				'init'=>array(
					array('name'=>'不显示','value'=>'N'),
					array('name'=>'显示','value'=>'Y'),
				),
				'defaultValue'=>'Y',
			),
			'template'=>array(
				'name'=>'模板',
				'type'=>'input',
				'defaultValue'=>"",
			),
		),
	),
	'composelist'=>array(
		'name'=>'录入文章',
		'note'=>'文章列表［单个/多个］（由管理员录入）',
		'appact'=>'page_composeContent,page_composeArticle',
		'admin'=>array(
			array('title'=>'管理','link'=>'setup/composeContent.php?pid=$pid&tab=home&appid=$itemid'),
		),
		'config'=>array(
			'multi'=>array(
				'name'=>'单元数量',
				'type'=>'input',
				'defaultValue'=>1,
			),
			'picnums'=>array(
				'name'=>'图片数量',
				'type'=>'input',
				'defaultValue'=>1,
			),
			'itemnum'=>array(
				'name'=>'单元长度',
				'type'=>'input',
				'defaultValue'=>10,
			),
			'titleLength'=>array(
				'name'=>'标题长度',
				'type'=>'input',
				'defaultValue'=>20,
			),
			'sumaryLength'=>array(
				'name'=>'描述长度',
				'type'=>'input',
				'defaultValue'=>100,
			),
			'datetime'=>array(
				'name'=>'日期显示',
				'type'=>'select',
				'init'=>array(
					array('name'=>'不显示','value'=>'none'),
					array('name'=>'2000-02-28 15:20','value'=>'type1'),
					array('name'=>'2000年02月28日 15:20','value'=>'type2'),
				),
				'defaultValue'=>'none',
			),
			'picnums'=>array(
				'name'=>'图片数量',
				'type'=>'input',
				'defaultValue'=>0,
			),
			'type'=>array(
				'name'=>'类型',
				'type'=>'radio',
				'init'=>array(
					array('name'=>'图片','value'=>'picture'),
					array('name'=>'视频','value'=>'video'),
				),
				'defaultValue'=>'picture',
			),
			'width'=>array(
				'name'=>'宽度',
				'type'=>'input',
				'defaultValue'=>200,
			),
			'height'=>array(
				'name'=>'高度',
				'type'=>'input',
				'defaultValue'=>150,
			),
			'picTitleLength'=>array(
				'name'=>'标题长度',
				'type'=>'input',
				'defaultValue'=>40,
			),
			'picSumaryLength'=>array(
				'name'=>'描述长度',
				'type'=>'input',
				'defaultValue'=>100,
			),
			'fields'=>array(
				'name'=>'显示要素',
				'type'=>'checkbox',
				'init'=>array(
					array('name'=>'图片/视频','value'=>'box'),
					array('name'=>'描述摘要','value'=>'text'),
					array('name'=>'内容编辑器','value'=>'editor'),
				),
				'defaultValue'=>'box,text',
			),
			'islist'=>array(
				'name'=>'列表页导航',
				'type'=>'select',
				'init'=>array(
					array('name'=>'不显示','value'=>'N'),
					array('name'=>'显示','value'=>'Y'),
				),
				'defaultValue'=>'Y',
			),
			'orderType'=>array(
				'name'=>'内容排序',
				'type'=>'select',
				'init'=>array(
					array('name'=>'正序','value'=>'ASC'),
					array('name'=>'倒序','value'=>'DESC'),
				),
				'defaultValue'=>'DESC',
			),
			'template'=>array(
				'name'=>'模板',
				'type'=>'input',
				'defaultValue'=>"",
			),
		),
	),
	'selectlist'=>array(
		'name'=>'推荐内容',
		'note'=>'单个列表［单个］（由管理员从其它数据单元选择推荐）',
		'appact'=>'page_selectlist',
		'admin'=>array(
			array('title'=>'管理','link'=>'setup/selectlist.php?pid=$pid&tab=home&appid=$itemid'),
		),
		'config'=>array(
			'app'=>array(
				'name'=>'推荐程序',
				'type'=>'select',
				
				/**
				 * 下面设置的所有程序，均指向 AppName/Lib/APP_page_plugins.php
				 * 默认调用方法：
				 * getCommend[result,select list],saveCommend
				 */
				'init'=>array(
					'bbs'=>array('name'=>'帖子','value'=>'bbs','tpl'=>'user'),
					'article'=>array('name'=>'文章','value'=>'article','tpl'=>'index'),
					//'bbs'=>array('name'=>'视频','value'=>'video','tpl'=>'pictext'),
					//'bbs'=>array('name'=>'博文','value'=>'blog','tpl'=>'user'),
					'download'=>array('name'=>'文档','value'=>'download','tpl'=>'pictext'),
					//'bbs'=>array('name'=>'网友讨论','value'=>'talk','tpl'=>'user'),
					//'bbs'=>array('name'=>'图书','value'=>'book','tpl'=>'pictext'),
					//'bbs'=>array('name'=>'专题','value'=>'topic','tpl'=>'pictext'),
					//'bbs'=>array('name'=>'活动','value'=>'event','tpl'=>'pictext'),
					//'bbs'=>array('name'=>'小组','value'=>'group','tpl'=>'user'),
					//'bbs'=>array('name'=>'商圈','value'=>'biz','tpl'=>'user'),
					//'bbs'=>array('name'=>'产品','value'=>'prodserv','tpl'=>'pictext'),
					'member'=>array('name'=>'用户','value'=>'member','tpl'=>'user'),
				),
				'defaultValue'=>'article',
			),
			'param'=>array(
				'name'=>'调用参数',
				'type'=>'input',
				'defaultValue'=>"x:1,y:2,z:3,....",
			),
			'itemnum'=>array(
				'name'=>'单元长度',
				'type'=>'input',
				'defaultValue'=>10,
			),
			'titleLengh'=>array(
				'name'=>'标题长度',
				'type'=>'input',
				'defaultValue'=>20,
			),
			'sumaryLengh'=>array(
				'name'=>'描述长度',
				'type'=>'input',
				'defaultValue'=>100,
			),
			'datetime'=>array(
				'name'=>'日期显示',
				'type'=>'select',
				'init'=>array(
					array('name'=>'不显示','value'=>'none'),
					array('name'=>'2000-02-28 15:20','value'=>'type1'),
					array('name'=>'2000-02-28 15:20','value'=>'type1'),
				),
				'defaultValue'=>'none',
			),
			
			'islist'=>array(
				'name'=>'列表页导航',
				'type'=>'select',
				'init'=>array(
					array('name'=>'不显示','value'=>'N'),
					array('name'=>'显示','value'=>'Y'),
				),
				'defaultValue'=>'Y',
			),
		),
	),
	'excute'=>array(
		'name'=>'单元调用',
		'note'=>'外调的程序单元，如调用id为123的调查程序：[survey:123]',
		'admin'=>array(
		),
		'config'=>array(
			'app'=>array(
				'name'=>'单元名称',
				'type'=>'input',
				'defaultValue'=>'article',
			),
			'class'=>array(
				'name'=>'执行命令',
				'type'=>'input',
				'defaultValue'=>'page_plugins',
			),
			'method'=>array(
				'name'=>'功能函数',
				'type'=>'input',
				'defaultValue'=>'get',
			),
			'param'=>array(
				'name'=>'调用参数',
				'type'=>'input',
				'defaultValue'=>"x:1,y:2,z:3,....",
			),
		),
	),
	'diagram'=>array(
		'name'=>'评测图表',
		'note'=>'示意图 ，建立，录入对比数据，并调用js效果图，实现图表呈现',
		'admin'=>array(
			array('title'=>'管理','link'=>'?mid=$pid&label=$itemlabel'),
		),
	),
	'compare'=>array(
		'name'=>'对比单元',
		'note'=>'录入对比内容，定义对比单元',
		'admin'=>array(
			array('title'=>'管理','link'=>'?mid=$pid&label=$itemlabel'),
		),
	),
	'html'=>array(
		'name'=>'网页代码',
		'note'=>'直接输出HTML或JS代码; ',
		'admin'=>array(
			array('title'=>'管理','link'=>'?mid=$pid&label=$itemlabel'),
		),
	),
	
);