export default {
    
        'zh-CN': {
          font: {
            bold: '粗体',
            italic: '斜体',
            underline: '下划线',
            clear: '清除格式',
            height: '行高',
            name: '字体',
            strikethrough: '删除线',
            subscript: '下标',
            superscript: '上标',
            size: '字号',
          },
          image: {
            image: '图片',
            insert: '插入图片',
            resizeFull: '缩放至 100%',
            resizeHalf: '缩放至 50%',
            resizeQuarter: '缩放至 25%',
            floatLeft: '靠左浮动',
            floatRight: '靠右浮动',
            floatNone: '取消浮动',
            shapeRounded: '形状: 圆角',
            shapeCircle: '形状: 圆',
            shapeThumbnail: '形状: 缩略图',
            shapeNone: '形状: 无',
            dragImageHere: '将图片拖拽至此处',
            dropImage: '拖拽图片或文本',
            selectFromFiles: '从本地上传',
            maximumFileSize: '文件大小最大值',
            maximumFileSizeError: '文件大小超出最大值。',
            url: '图片地址',
            remove: '移除图片',
            original: '原始图片',
          },
          video: {
            video: '视频',
            videoLink: '视频链接',
            insert: '插入视频',
            url: '视频地址',
            providers: '(优酷, 腾讯, Instagram, DailyMotion, Youtube等)',
          },
          link: {
            link: '链接',
            insert: '插入链接',
            unlink: '去除链接',
            edit: '编辑链接',
            textToDisplay: '显示文本',
            url: '链接地址',
            openInNewWindow: '在新窗口打开',
          },
          table: {
            table: '表格',
            addRowAbove: '在上方插入行',
            addRowBelow: '在下方插入行',
            addColLeft: '在左侧插入列',
            addColRight: '在右侧插入列',
            delRow: '删除行',
            delCol: '删除列',
            delTable: '删除表格',
          },
          hr: {
            insert: '水平线',
          },
          style: {
            style: '样式',
            p: '普通',
            blockquote: '引用',
            pre: '代码',
            h1: '标题 1',
            h2: '标题 2',
            h3: '标题 3',
            h4: '标题 4',
            h5: '标题 5',
            h6: '标题 6',
          },
          lists: {
            unordered: '无序列表',
            ordered: '有序列表',
          },
          options: {
            help: '帮助',
            fullscreen: '全屏',
            codeview: '源代码',
          },
          paragraph: {
            paragraph: '段落',
            outdent: '减少缩进',
            indent: '增加缩进',
            left: '左对齐',
            center: '居中对齐',
            right: '右对齐',
            justify: '两端对齐',
          },
          color: {
            recent: '最近使用',
            more: '更多',
            background: '背景',
            foreground: '前景',
            transparent: '透明',
            setTransparent: '透明',
            reset: '重置',
            resetToDefault: '默认',
          },
          shortcut: {
            shortcuts: '快捷键',
            close: '关闭',
            textFormatting: '文本格式',
            action: '动作',
            paragraphFormatting: '段落格式',
            documentStyle: '文档样式',
            extraKeys: '额外按键',
          },
          help: {
            insertParagraph: '插入段落',
            undo: '撤销',
            redo: '重做',
            tab: '增加缩进',
            untab: '减少缩进',
            bold: '粗体',
            italic: '斜体',
            underline: '下划线',
            strikethrough: '删除线',
            removeFormat: '清除格式',
            justifyLeft: '左对齐',
            justifyCenter: '居中对齐',
            justifyRight: '右对齐',
            justifyFull: '两端对齐',
            insertUnorderedList: '无序列表',
            insertOrderedList: '有序列表',
            outdent: '减少缩进',
            indent: '增加缩进',
            formatPara: '设置选中内容样式为 普通',
            formatH1: '设置选中内容样式为 标题1',
            formatH2: '设置选中内容样式为 标题2',
            formatH3: '设置选中内容样式为 标题3',
            formatH4: '设置选中内容样式为 标题4',
            formatH5: '设置选中内容样式为 标题5',
            formatH6: '设置选中内容样式为 标题6',
            insertHorizontalRule: '插入水平线',
            'linkDialog.show': '显示链接对话框',
          },
          history: {
            undo: '撤销',
            redo: '重做',
          },
          specialChar: {
            specialChar: '特殊字符',
            select: '选取特殊字符',
          },
        },
        'zh-TW': {
            font: {
              bold: '粗體',
              italic: '斜體',
              underline: '底線',
              clear: '清除格式',
              height: '行高',
              name: '字體',
              strikethrough: '刪除線',
              subscript: '下標',
              superscript: '上標',
              size: '字號',
            },
            image: {
              image: '圖片',
              insert: '插入圖片',
              resizeFull: '縮放至100%',
              resizeHalf: '縮放至 50%',
              resizeQuarter: '縮放至 25%',
              floatLeft: '靠左浮動',
              floatRight: '靠右浮動',
              floatNone: '取消浮動',
              shapeRounded: '形狀: 圓角',
              shapeCircle: '形狀: 圓',
              shapeThumbnail: '形狀: 縮略圖',
              shapeNone: '形狀: 無',
              dragImageHere: '將圖片拖曳至此處',
              dropImage: 'Drop image or Text',
              selectFromFiles: '從本機上傳',
              maximumFileSize: '文件大小最大值',
              maximumFileSizeError: '文件大小超出最大值。',
              url: '圖片網址',
              remove: '移除圖片',
              original: 'Original',
            },
            video: {
              video: '影片',
              videoLink: '影片連結',
              insert: '插入影片',
              url: '影片網址',
              providers: '(優酷, Instagram, DailyMotion, Youtube等)',
            },
            link: {
              link: '連結',
              insert: '插入連結',
              unlink: '取消連結',
              edit: '編輯連結',
              textToDisplay: '顯示文字',
              url: '連結網址',
              openInNewWindow: '在新視窗開啟',
            },
            table: {
              table: '表格',
              addRowAbove: 'Add row above',
              addRowBelow: 'Add row below',
              addColLeft: 'Add column left',
              addColRight: 'Add column right',
              delRow: 'Delete row',
              delCol: 'Delete column',
              delTable: 'Delete table',
            },
            hr: {
              insert: '水平線',
            },
            style: {
              style: '樣式',
              p: '一般',
              blockquote: '引用區塊',
              pre: '程式碼區塊',
              h1: '標題 1',
              h2: '標題 2',
              h3: '標題 3',
              h4: '標題 4',
              h5: '標題 5',
              h6: '標題 6',
            },
            lists: {
              unordered: '項目清單',
              ordered: '編號清單',
            },
            options: {
              help: '幫助',
              fullscreen: '全螢幕',
              codeview: '原始碼',
            },
            paragraph: {
              paragraph: '段落',
              outdent: '取消縮排',
              indent: '增加縮排',
              left: '靠右對齊',
              center: '靠中對齊',
              right: '靠右對齊',
              justify: '左右對齊',
            },
            color: {
              recent: '字型顏色',
              more: '更多',
              background: '背景',
              foreground: '前景',
              transparent: '透明',
              setTransparent: '透明',
              reset: '重設',
              resetToDefault: '默認',
            },
            shortcut: {
              shortcuts: '快捷鍵',
              close: '關閉',
              textFormatting: '文字格式',
              action: '動作',
              paragraphFormatting: '段落格式',
              documentStyle: '文件格式',
              extraKeys: '額外按鍵',
            },
            help: {
              'insertParagraph': 'Insert Paragraph',
              'undo': 'Undoes the last command',
              'redo': 'Redoes the last command',
              'tab': 'Tab',
              'untab': 'Untab',
              'bold': 'Set a bold style',
              'italic': 'Set a italic style',
              'underline': 'Set a underline style',
              'strikethrough': 'Set a strikethrough style',
              'removeFormat': 'Clean a style',
              'justifyLeft': 'Set left align',
              'justifyCenter': 'Set center align',
              'justifyRight': 'Set right align',
              'justifyFull': 'Set full align',
              'insertUnorderedList': 'Toggle unordered list',
              'insertOrderedList': 'Toggle ordered list',
              'outdent': 'Outdent on current paragraph',
              'indent': 'Indent on current paragraph',
              'formatPara': 'Change current block\'s format as a paragraph(P tag)',
              'formatH1': 'Change current block\'s format as H1',
              'formatH2': 'Change current block\'s format as H2',
              'formatH3': 'Change current block\'s format as H3',
              'formatH4': 'Change current block\'s format as H4',
              'formatH5': 'Change current block\'s format as H5',
              'formatH6': 'Change current block\'s format as H6',
              'insertHorizontalRule': 'Insert horizontal rule',
              'linkDialog.show': 'Show Link Dialog',
            },
            history: {
              undo: '復原',
              redo: '取消復原',
            },
            specialChar: {
              specialChar: 'SPECIAL CHARACTERS',
              select: 'Select Special characters',
            },
          }

}