<?php
return array(
	'info'=>array(
		1=>array(
		 "host"=>"192.168.100.185",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		2=>array(
		 "host"=>"192.168.100.160",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		3=>array(
		 "host"=>"192.168.100.196",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		4=>array(
		 "host"=>"192.168.100.175",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		5=>array(
		 "host"=>"192.168.100.195",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		6=>array(
		 "host"=>"192.168.100.155",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		7=>array(
		 "host"=>"192.168.100.180",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
		8=>array(
		 "host"=>"192.168.100.83",
		 "user"=>"root",
		 "pass"=>'jgaoabj',
		),
	),
	
	'db'=>array(
		array(1,'wxc_main'),
		array(1,'wxc_user'),
		array(1,'wxc_book'),
		array(1,'wxc_career'),
		array(1,'wxc_count'),
		array(1,'wxc_signature'),
		array(1,'wxc_topic'),
		array(1,'wxc_campaigns'),
		array(1,'wxc_user'),
		array(1,'wxc_userdata'),
		array(1,'wxcnews'),
		
		//bbs
		array(7,'wxc_bbs0'),
		array(7,'wxc_bbs1'),
		array(7,'wxc_bbs2'),
		array(2,'wxc_bbs3'),
		array(2,'wxc_bbs4'),
		array(2,'wxc_bbs5'),
		array(2,'wxc_bbs6'),
		array(2,'wxc_myspace'),
		array(5,'wxc_shared'),
			
		//members
		array(8,'wxc_cachemark'),
		array(8,'wxc_group'),
		array(8,'wxc_members'),
		array(8,'wxc_pm'),
		
		//blog
		array(4,'lifeyp'),
		array(4,'wxc_blog'),
		
		//其它
		array(3,'avcforum'),
		array(3,'Cronjob'),
		
		//电信
		array(6,'get800today'),
		array(6,'online800'),
		array(6,'pbxbusiness'),
		array(6,'pbxplans'),
		array(6,'wxc_dialnopin'),
		array(6,'wxc_online800'),
	),
);
?>